mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^register/', register_view, name="register"),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^', include("posts.urls", namespace="posts")),
    url(r'^api/posts/', include("posts.api.urls", namespace='posts-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import url
from .views import (
	PostCreateAPIView,
	PostDeleteAPIView,
	PostDetailAPIView,
	PostListAPIView,
	PostUpdateAPIView,
	)

urlpatterns = [
	url(r'^$', PostListAPIView.as_view(), name="list"),
	url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
	url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name="detail"),
	url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name="update"),
	url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name="delete"),
	#url(r'^posts/$', <appname>.views.<function_name>),
]

posts/urls.py
from django.conf.urls import url
from .views import (
		post_list,
		post_create,
		post_detail,
		post_update,
		post_delete,
	)

urlpatterns = [
	url(r'^$', post_list, name="list"),
	url(r'^create/$', post_create),
	url(r'^(?P<slug>[\w-]+)/$', post_detail, name="detail"),
	url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name="update"),
	url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
	#url(r'^posts/$', <appname>.views.<function_name>),
]

posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save

from django.utils.text import slugify
from django.utils import timezone
from django.utils.safestring import mark_safe

from markdown_deux import markdown
from comments.models import Comment
from .utils import get_read_time

# Create your models here.
# MVC MODEL VIEW CONTROLLER

#Post.objects.all()
#Post.objects.create(user=user, title="some time")
class PostManager(models.Manager):
	def active(self, *args, **kwargs):
		# Post.objects.all() = super(PostManager, self).all()
		return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
	# filebase, extension = filename.split(".")
	# return"%s/%s.%s" %(instance.id, instance.id, extension)
	return"%s/%s" %(instance.id, filename)

class Post(models.Model):
	user 	  = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	title 	  = models.CharField(max_length=120) # required = max_length=120
	slug	  = models.SlugField(unique=True)
	image	  = models.ImageField(upload_to=upload_location,
				null=True, 
				blank=True, 
				width_field="width_field",
				height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	content   = models.TextField()
	draft	  = models.BooleanField(default=False)
	publish	  = models.DateField(auto_now=False, auto_now_add=False)
	read_time = models.IntegerField(default=0) # models.TimeField(null=True, blank=True) #assume minutes
	updated   = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


	objects = PostManager()

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"slug" : self.slug})

	class Meta:
		ordering = ["-timestamp", "-updated"]

	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		return mark_safe(markdown_text)

	@property
	def comments(self):
		instance = self
		qs = Comment.objects.filter_by_instance(instance)
		return qs
	
	@property
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type

def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)

	if instance.content:
		html_string = instance.get_markdown()
		read_time_var = get_read_time(html_string)
		instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post

class PostForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(widget=forms.SelectDateWidget)
	class Meta:
		model = Post
		fields = [
			'title',
			'content',
			'image',
			'draft',
			'publish',
		]

posts/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView

from rest_framework.generics import (
	CreateAPIView,
	DestroyAPIView,
	ListAPIView,
	UpdateAPIView,
	RetrieveAPIView,
	RetrieveUpdateAPIView
	)

from posts.models import Post
from .serializers import (
	PostCreateUpdateSerializer, 
	PostListSerializer, 
	PostDetailSerializer
	)

class PostCreateAPIView(CreateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostCreateUpdateSerializer

	def perform_create(self, serializer):
		serializer.save(user=self.request.user)

class PostDetailAPIView(RetrieveAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	lookup_field = 'slug'
	#lookup_url_kwarg = 'abc'

class PostUpdateAPIView(RetrieveUpdateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostCreateUpdateSerializer
	lookup_field = 'slug'
	#lookup_url_kwarg = 'abc'
	def perform_update(self, serializer):
		serializer.save(user=self.request.user)

class PostDeleteAPIView(DestroyAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	lookup_field = 'slug'
	#lookup_url_kwarg = 'abc'

class PostListAPIView(ListAPIView):
	queryset = Post.objects.all()
	serializer_class = PostListSerializer

posts/views.py
from urllib import quote_plus
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.utils import timezone
from django.db.models import Q

from comments.forms import CommentForm
from .models import Post
from .forms import PostForm
from comments.models import Comment

def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404

	# if not request.user.is_authenticated():
	# 	raise Http404

	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		messages.success(request,"Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		'form': form,
	}
	return render(request, "post_form.html", context)

def post_detail(request, slug=None): 
	instance = get_object_or_404(Post, slug=slug)
	if instance.publish > timezone.now().date() or instance.draft:
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	share_string = quote_plus(instance.content)


	initial_data = {
		"content_type": instance.get_content_type,
		"object_id": instance.id,
	}

	form = comment_form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid() and request.user.is_authenticated():
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get("object_id")
		content_data = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()

		new_comment, created = Comment.objects.get_or_create(
							user = request.user,
							content_type = content_type,
							object_id = obj_id,
							content = content_data,
							parent = parent_obj,
						)
		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

	comments = instance.comments

	context = {
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
		"comments": comments,
		'comment_form': form,
	}
	return render(request, "post_detail.html", context)

def post_list(request): 
	today = timezone.now().date()
	queryset_list = Post.objects.active() #.order_by("-timestamp")
	if request.user.is_staff or request.user.is_superuser:
		queryset_list =  Post.objects.all()
	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
			Q(title__icontains=query) |
			Q(content__icontains=query) |
			Q(user__first_name__icontains=query) |
			Q(user__last_name__icontains=query)
			).distinct()
	paginator = Paginator(queryset_list, 2) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	
	
	context = {
			"object_list" : queryset,
	 		"title": "list",
	 		"page_request_var": page_request_var,
	 		"today": today
	}
	return render(request, "post_list.html", context)



def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance,)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item </a>Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())
	
	context = {
		"title": instance.title,
		"instance": instance,
		"form": form
	}
	return render(request, "post_form.html", context)

def post_delete(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request,"Successfully Deleted")
	return redirect("posts:list")
	
	return render(request, "<h1>Delete!</h1>")

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block title %} My Blog{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<!-- font Awesome --->
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></li>

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
 <style type="text/css">
 {% block style %}{% endblock %}
 </style>
 {% block head_extra %}{% endblock %}
</head>
<body>
	<div id="fb-root"></div>
	<script async defer src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2"></script>

	{% include "messages_display.html" %}
	<div class="container">
		<ol class="breadcrumb">
			<li><a href="{% url 'posts:list' %}">Home</a></li>
			<!-- <li><a href="{% url 'posts:list' %}">Post</a></li> -->
			{% block post_detail_link %}
			{% endblock %}

			{% if not request.user.is_authenticated %}
			<li class="pull-right"><a href="{% url 'register' %}">Register</a></li>
			<li class="pull-right"><a href="{% url 'login' %}">Login</a></li>		
			{% else %}		
			<li class="pull-right"><a href="{% url 'logout' %}">Logout</a></li>
			{% endif %}
		</ol>
		{% block content %}{% endblock %}
	</div>

	<script src="https://code.jquery.com/jquery-1.12.2.min.js"
	integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
	crossorigin="anonymous"></script>


	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.1/marked.js"></script>

	<scritp src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.1/marked.min.js"></scritp>
	<script type="text/javascript">
		$(document).ready(function(){
			$(".content-markdown").each(function(){
				var content = $(this).text()
				var markedContent = marked(content)
				$(this).html(markedContent)
		    })
		    $(".post-detail-item img").each(function(){
		    	$(this).addClass("img-responsive");
		    })



		    var contentInput = $("#id_content");

		    function setContent(value){
		    	var markedContent = marked(value)
		    	$("#preview-content").html(markedContent)
		    	$("#preview-content img").each(function(){
		    		$(this).addClass("img-responsive")
		    	})
		    }

		    setContent(contentInput.val())

		    contentInput.keyup(function(){
		    	var newContent = $(this).val()
		    	setContent(newContent)
		    })

		    var titleInput = $("#id_title");


		    function setTitle(value) {
		    	$("#preview-title").text(value)
		    }
		    setTitle(titleInput.val())

		    titleInput.keyup(function() {
		    	var newContent = $(this).val()
		    	setTitle(newContent)		    	
		    })

		    $(".comment-reply-btn").click(function(event){
		    	event.preventDefault();
		    	$(this).parent().next(".comment-reply").fadeToggle();
		    })
		    // preview-title
		    // preview-content
		})
	</script>

</body>
</html>

templates/comment_thread.html
{% extends 'base.html' %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block title %}{{ instance.title }} | {{ block.super }}{% endblock %}

{% block content %}
{{ object }}

<div class="col-md-6 col-sm-offset-3">
		
		<p>{{ comment.content }}</p>
		<footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %}{% endif %}{% if request.user == comment.user %}<a href="{{ comment.get_delete_url }}">Delete</a>{% endif %}</footer>
		<hr>
		<div>
			{% for child_comment in comment.children %}
				<blockquote>
					<p>{{ child_comment.content }}</p>
					<footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago |{% if request.user == child_comment.user %}<a href="{{ child_comment.get_delete_url }}">Delete</a>{% endif %}</footer>
				</blockquote>
			{% endfor %}
			{% if request.user.is_authenticated %}
			<form method="POST" action=".">
				{% csrf_token %}
				{{ form|crispy }}
				<input type="hidden" name="parent_id" value="{{ comment.id }}">
				<input type="submit" value="Reply" class="btn btn-default">
			</form>
			{% else %}
			<p>You must login to comment</p>
			{% endif %}
		</div>

		<hr>

</div>
{% endblock content %}

templates/confirm_delete.html
{% extends 'base.html' %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block title %}{{ instance.title }} | {{ block.super }}{% endblock %}

{% block content %}


<div class="col-md-6 col-sm-offset-3">

	<h1>Confirm Delete</h1>
			<form method="POST" action=".">
				{% csrf_token %}
				<p>Are you sure you want to delete: "{{ object.content }}"?</p>
				<input type="submit" value="Confirm" class="btn btn-warning">
				<a href="{{ object.get_absolute_url }}" class="btn btn-default">Cancel</a>
			</form>
		</div>

		<hr>

</div>
{% endblock content %}

templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="col-sm-6 col-sm-offset-3">
	<h1>{{ title }}</h1>
	<hr>
	<form method="POST" action='' enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" class="btn btn-default" value="{{ title }}">
	</form>
</div>	
{% endblock content %}

templates/messages_display.html
{% if messages %}
    <div class="messages">
		<ul class="messages">
		    {% for message in messages %}
		    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
		    {% endfor %}
		</ul>
	</div>
{% endif %}

templates/post_detail.html
{% extends 'base.html' %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block title %}{{ instance.title }} | {{ block.super }}{% endblock %}

{% block post_detail_link %}
<li><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>

{% endblock %}

{% block content %}
<div class="col-md-6 col-sm-offset-3">

	{% if instance.image %}
	<img src="{{ instance.image.url }}" class="img-responsive">
	{% endif %}
	
	<h1>{{ title }} <small>
	
	{% if instance.draft %}
	<span style="color:red;">Draft</span>
	{% endif %}
	
	{{ instance.publish }}
	</small></h1>

	<p>Read time: {% if instance.read_time <= 1 %} < 1 Minute {% else %}{{ instance.read_time }} minutes{% endif %}</p>
	{% if instance.user.get_full_name %}
	<p>Author: {{ instance.user.get_full_name }}</p>
	{% endif %}
	
	<p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>
	<hr>
	
<!-- 	<p>
	<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
Facebook
</a>
	<a href="https://twitter.com/home?status={{ instance.content|truncatechars:80|urlify }}%20{{ request.build_absolute_uri }}">
Twitter
</a>
	<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>Google+</a>
	<a href="https://www.linkedin.com/shareArticle?mini=true&url=http://swiftforentrepreneurs.com/&title={{ instance.title }}&summary={{ share_string }} &source={{ request.build_absolute_uri }}">
Linkedin
</a>
	</p> -->
<div class="row">
	<div class="col-sm-12">
		<!-- {{ instance.title }}<br> -->
		<div class="post-detail-item">{{ instance.get_markdown }}</div>
		
 		<!-- {{ instance.comments.all }} -->
		<hr>
		<br>

		<div>
			<p class='lead'>Comments</p>
			{% if request.user.is_authenticated %}
			<form method="POST" action=".">
				{% csrf_token %}
				{{ comment_form|crispy }}
				<input type="submit" value="Post comment" class="btn btn-default">
			</form>
			{% else %}
			<p> You must login to comment</p>
			{% endif %}
			<hr>
			{% for comment in comments %}
			
			<blockquote>
				<p>{{ comment.content }}</p>
				<footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %}<a class="comment-reply-btn" href="#">Reply</a> | <a href="{{ comment.get_absolute_url }}">Thread</a></footer>
				<div class="comment-reply">
					{% for child_comment in comment.children %}
						<blockquote>
							<p>{{ child_comment.content }}</p>
							<footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
						</blockquote>
					{% endfor %}
					{% if request.user.is_authenticated %}
					<form method="POST" action=".">
						{% csrf_token %}
						{{ comment_form|crispy }}
						<input type="hidden" name="parent_id" value="{{ comment.id }}">
						<input type="submit" value="Reply" class="btn btn-default">
					</form>
					{% else %}
					<p>You must login to reply</p>
					{% endif %}
				</div>
			</blockquote>

			<hr>

			{% endfor %}
		</div>

	</div>
</div>

</div>
{% endblock content %}

templates/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_extra %}
	{{ form.media }}
{% endblock %}

{% block content %}
<div class="col-sm-6">
	<h1>Preview</h1>
	<hr>
	<div class="content-preview">
		<h3 id="preview-title"></h3>
		<p id="preview-content"></p>
	</div>
</div>
<div class="col-sm-6">
	<h1>form</h1>
	<hr>
	<form method="POST" action='' enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" class="btn btn-default" value="Create Post">
	</form>
</div>	
{% endblock content %}

templates/post_list.html
{% extends 'base.html' %}

{% block content %}

<div class="col-sm-6 col-md-offset-2">
	<h1>{{ title }} is working</h1>

	<form method="GET" action="" class="row">
		<div class="col-sm-6">
			<div class="input-group">
				<input class="form-control" type="text" name="q" placeholder="Search post" value="{{ request.GET.q }}">
				<span class="input-group-btn">
					<!-- <input class="btn btn-default" type="submit" value="Search"> -->
					<button class="btn btn-default" type="button">Search <i class="fa fa-search" aria-hidden="true"></i>
</button>
				</span>
			</div>
		</div>
	</form>
 	<br>
	{% for obj in object_list %}
	<div class="row">
		<div class="col-sm-12">
			<div class="thumbnail">
			
			{% if obj.image %}
		     <img src="{{ obj.image.url }}" class="img-responsive">
		     {% endif %}
		    
		      <div class="caption post-detail-item">
		      	{% if obj.draft %}<h3 style="color: red;">Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff only: Future Post </h3>{% endif %}
		        <h3><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a> <small>{{ obj.publish }}</small></h3>

		        {% if obj.user.get_full_name %}
		        <p>Author: {{ obj.user.get_full_name }}</p>
		        {% endif %}

		        {{ obj.get_markdown|truncatechars_html:120 }}
		        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">view</a></p>
		      </div>
		    </div>
		  </div>
	</div>
	<!-- {% cycle "" "<div class='col-sm-12'><hr></div><div class='row'>" %} -->
	{% endfor %}
	
	<div class="pagination">
	    <span class="step-links">
	        {% if object_list.has_previous %}
	            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
	        {% endif %}

	        <span class="current">
	            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
	        </span>

	        {% if object_list.has_next %}
	            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
	        {% endif %}
	    </span>
	</div>

</div>
	
{% endblock content %}